(in-package :visa32)

(define-foreign-library visa32
  (:win32 "visa32.dll"))

;;(use-foreign-library visa32)

(defmacro defvisa32constant (name value &optional doc)
  "Wrapper around `defconstant' which exports the constant."
  `(progn
     (eval-when (:compile-toplevel :load-toplevel :execute)
       (defparameter ,name ,value ,doc))
     (export ',name)))

;; Attributes (platform independent size)
(defvisa32constant +vi_attr_rsrc_class+               #xBFFF0001)
(defvisa32constant +vi_attr_rsrc_name+                #xBFFF0002)
(defvisa32constant +vi_attr_rsrc_impl_version+        #x3FFF0003)
(defvisa32constant +vi_attr_rsrc_lock_state+          #x3FFF0004)
(defvisa32constant +vi_attr_max_queue_length+         #x3FFF0005)
(defvisa32constant +vi_attr_user_data_32+             #x3FFF0007)
(defvisa32constant +vi_attr_fdc_chnl+                 #x3FFF000D)
(defvisa32constant +vi_attr_fdc_mode+                 #x3FFF000F)
(defvisa32constant +vi_attr_fdc_gen_signal_en+        #x3FFF0011)
(defvisa32constant +vi_attr_fdc_use_pair+             #x3FFF0013)
(defvisa32constant +vi_attr_termchar+                 #x3FFF0018)
(defvisa32constant +vi_attr_tmo_value+                #x3FFF001A)
(defvisa32constant +vi_attr_gpib_readdr_en+           #x3FFF001B)
(defvisa32constant +vi_attr_io_prot+                  #x3FFF001C)
(defvisa32constant +vi_attr_dma_allow_en+             #x3FFF001E)
(defvisa32constant +vi_attr_asrl_baud+                #x3FFF0021)
(defvisa32constant +vi_attr_asrl_data_bits+           #x3FFF0022)
(defvisa32constant +vi_attr_asrl_parity+              #x3FFF0023)
(defvisa32constant +vi_attr_asrl_stop_bits+           #x3FFF0024)
(defvisa32constant +vi_attr_asrl_flow_cntrl+          #x3FFF0025)
(defvisa32constant +vi_attr_rd_buf_oper_mode+         #x3FFF002A)
(defvisa32constant +vi_attr_wr_buf_oper_mode+         #x3FFF002D)
(defvisa32constant +vi_attr_wr_buf_size+              #x3FFF002E)
(defvisa32constant +vi_attr_suppress_end_en+          #x3FFF0036)
(defvisa32constant +vi_attr_termchar_en+              #x3FFF0038)
(defvisa32constant +vi_attr_dest_access_priv+         #x3FFF0039)
(defvisa32constant +vi_attr_dest_byte_order+          #x3FFF003A)
(defvisa32constant +vi_attr_src_access_priv+          #x3FFF003C)
(defvisa32constant +vi_attr_src_byte_order+           #x3FFF003D)
(defvisa32constant +vi_attr_src_increment+            #x3FFF0040)
(defvisa32constant +vi_attr_dest_increment+           #x3FFF0041)
(defvisa32constant +vi_attr_win_access_priv+          #x3FFF0045)
(defvisa32constant +vi_attr_win_byte_order+           #x3FFF0047)
(defvisa32constant +vi_attr_gpib_atn_state+           #x3FFF0057)
(defvisa32constant +vi_attr_gpib_addr_state+          #x3FFF005C)
(defvisa32constant +vi_attr_gpib_cic_state+           #x3FFF005E)
(defvisa32constant +vi_attr_gpib_ndac_state+          #x3FFF0062)
(defvisa32constant +vi_attr_gpib_srq_state+           #x3FFF0067)
(defvisa32constant +vi_attr_gpib_sys_cntrl_state+     #x3FFF0068)
(defvisa32constant +vi_attr_gpbi_hs488_cbl_len+       #x3FFF0069)
(defvisa32constant +vi_attr_cmdr_la+                  #x3FFF006B)
(defvisa32constant +vi_attr_vxi_dev_class+            #x3FFF006C)
(defvisa32constant +vi_attr_mainframe_la+             #x3FFF0070)
(defvisa32constant +vi_attr_manf_name+                #x3FFF0072)
(defvisa32constant +vi_attr_model_name+               #xbFFF0077)
(defvisa32constant +vi_attr_vxi_vme_intr_status+      #x3FFF008B)
(defvisa32constant +vi_attr_vxi_trig_status+          #x3FFF008D)
(defvisa32constant +vi_attr_vxi_vme_sysfail_state+    #x3FFF0094)
(defvisa32constant +vi_attr_win_base_addr_32+         #x3FFF0098)
(defvisa32constant +vi_attr_win_size_32+              #x3FFF009A)
(defvisa32constant +vi_attr_asrl_avail_num+           #x3FFF00AC)
(defvisa32constant +vi_attr_mem_base_32+              #x3FFF00AD)
(defvisa32constant +vi_attr_asrl_cts_state+           #x3FFF00AE)
(defvisa32constant +vi_attr_asrl_dcd_state+           #x3FFF00AF)
(defvisa32constant +vi_attr_asrl_dsr_state+           #x3FFF00B1)
(defvisa32constant +vi_attr_asrl_dtr_state+           #x3FFF00B2)
(defvisa32constant +vi_attr_asrl_end_in+              #x3FFF00B3)
(defvisa32constant +vi_attr_asrl_end_out+             #x3FFF00B4)
(defvisa32constant +vi_attr_asrl_replace_char+        #x3FFF00BE)
(defvisa32constant +vi_attr_asrl_ri_state+            #x3FFF00BF)
(defvisa32constant +vi_attr_asrl_rts_state+           #x3FFF00C0)
(defvisa32constant +vi_attr_asrl_xon_char+            #x3FFF00C1)
(defvisa32constant +vi_attr_asrl_xoff_char+           #x3FFF00C2)
(defvisa32constant +vi_attr_win_access+               #x3FFF00C3)
(defvisa32constant +vi_attr_rm_session+               #x3FFF00C4)
(defvisa32constant +vi_attr_vxi_la+                   #x3FFF00D5)
(defvisa32constant +vi_attr_manf_id+                  #x3FFF00D9)
(defvisa32constant +vi_attr_mem_size_32+              #x3FFF00DD) 
(defvisa32constant +vi_attr_mem_space+                #x3FFF00DE)
(defvisa32constant +vi_attr_model_code+               #x3FFF00DF)
(defvisa32constant +vi_attr_slot+                     #x3FFF00E8)
(defvisa32constant +vi_attr_intf_inst_name+           #x3FFF00E9)
(defvisa32constant +vi_attr_immediate_serv+           #x3FFF0100)
(defvisa32constant +vi_attr_intf_parent_num+          #x3FFF0101)
(defvisa32constant +vi_attr_rsrc_spec_version+        #x3FFF0170)
(defvisa32constant +vi_attr_intf_type+                #x3FFF0171)
(defvisa32constant +vi_attr_gpib_primary_addr+        #x3FFF0172)
(defvisa32constant +vi_attr_gpbi_secondary_addr+      #x3FFF0173)
(defvisa32constant +vi_attr_rsrc_manf_name+           #xBFFF0174)
(defvisa32constant +vi_attr_rsrc_manf_id+             #x3FFF0175)
(defvisa32constant +vi_attr_intf_num+                 #x3FFF0176)
(defvisa32constant +vi_attr_trig_id+                  #x3FFF0177)
(defvisa32constant +vi_attr_gpib_ren_state+           #x3FFF0181)


#|

#define VI_ATTR_GPIB_UNADDR_EN                (0x3FFF0184UL)
#define VI_ATTR_DEV_STATUS_BYTE               (0x3FFF0189UL)
#define VI_ATTR_FILE_APPEND_EN                (0x3FFF0192UL)
#define VI_ATTR_VXI_TRIG_SUPPORT              (0x3FFF0194UL)
#define VI_ATTR_TCPIP_ADDR                    (0xBFFF0195UL)
#define VI_ATTR_TCPIP_HOSTNAME                (0xBFFF0196UL)
#define VI_ATTR_TCPIP_PORT                    (0x3FFF0197UL)
#define VI_ATTR_TCPIP_DEVICE_NAME             (0xBFFF0199UL)
#define VI_ATTR_TCPIP_NODELAY                 (0x3FFF019AUL)
#define VI_ATTR_TCPIP_KEEPALIVE               (0x3FFF019BUL)
#define VI_ATTR_4882_COMPLIANT                (0x3FFF019FUL)
#define VI_ATTR_USB_SERIAL_NUM                (0xBFFF01A0UL)
#define VI_ATTR_USB_INTFC_NUM                 (0x3FFF01A1UL)
#define VI_ATTR_USB_PROTOCOL                  (0x3FFF01A7UL)
#define VI_ATTR_USB_MAX_INTR_SIZE             (0x3FFF01AFUL)
#define VI_ATTR_PXI_DEV_NUM                   (0x3FFF0201UL)
#define VI_ATTR_PXI_FUNC_NUM                  (0x3FFF0202UL)
#define VI_ATTR_PXI_BUS_NUM                   (0x3FFF0205UL)
#define VI_ATTR_PXI_CHASSIS                   (0x3FFF0206UL)
#define VI_ATTR_PXI_SLOTPATH                  (0xBFFF0207UL)
#define VI_ATTR_PXI_SLOT_LBUS_LEFT            (0x3FFF0208UL)
#define VI_ATTR_PXI_SLOT_LBUS_RIGHT           (0x3FFF0209UL)
#define VI_ATTR_PXI_TRIG_BUS                  (0x3FFF020AUL)
#define VI_ATTR_PXI_STAR_TRIG_BUS             (0x3FFF020BUL)
#define VI_ATTR_PXI_STAR_TRIG_LINE            (0x3FFF020CUL)
#define VI_ATTR_PXI_SRC_TRIG_BUS              (0x3FFF020DUL)
#define VI_ATTR_PXI_DEST_TRIG_BUS             (0x3FFF020EUL)
#define VI_ATTR_PXI_MEM_TYPE_BAR0             (0x3FFF0211UL)
#define VI_ATTR_PXI_MEM_TYPE_BAR1             (0x3FFF0212UL)
#define VI_ATTR_PXI_MEM_TYPE_BAR2             (0x3FFF0213UL)
#define VI_ATTR_PXI_MEM_TYPE_BAR3             (0x3FFF0214UL)
#define VI_ATTR_PXI_MEM_TYPE_BAR4             (0x3FFF0215UL)
#define VI_ATTR_PXI_MEM_TYPE_BAR5             (0x3FFF0216UL)
#define VI_ATTR_PXI_MEM_BASE_BAR0_32          (0x3FFF0221UL)
#define VI_ATTR_PXI_MEM_BASE_BAR1_32          (0x3FFF0222UL)
#define VI_ATTR_PXI_MEM_BASE_BAR2_32          (0x3FFF0223UL)
#define VI_ATTR_PXI_MEM_BASE_BAR3_32          (0x3FFF0224UL)
#define VI_ATTR_PXI_MEM_BASE_BAR4_32          (0x3FFF0225UL)
#define VI_ATTR_PXI_MEM_BASE_BAR5_32          (0x3FFF0226UL)
#define VI_ATTR_PXI_MEM_BASE_BAR0_64          (0x3FFF0228UL)
#define VI_ATTR_PXI_MEM_BASE_BAR1_64          (0x3FFF0229UL)
#define VI_ATTR_PXI_MEM_BASE_BAR2_64          (0x3FFF022AUL)
#define VI_ATTR_PXI_MEM_BASE_BAR3_64          (0x3FFF022BUL)
#define VI_ATTR_PXI_MEM_BASE_BAR4_64          (0x3FFF022CUL)
#define VI_ATTR_PXI_MEM_BASE_BAR5_64          (0x3FFF022DUL)
#define VI_ATTR_PXI_MEM_SIZE_BAR0_32          (0x3FFF0231UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR1_32          (0x3FFF0232UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR2_32          (0x3FFF0233UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR3_32          (0x3FFF0234UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR4_32          (0x3FFF0235UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR5_32          (0x3FFF0236UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR0_64          (0x3FFF0238UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR1_64          (0x3FFF0239UL)
#define VI_ATTR_PXI_MEM_SIZE_BAR2_64          (0x3FFF023AUL)
#define VI_ATTR_PXI_MEM_SIZE_BAR3_64          (0x3FFF023BUL)
#define VI_ATTR_PXI_MEM_SIZE_BAR4_64          (0x3FFF023CUL)
#define VI_ATTR_PXI_MEM_SIZE_BAR5_64          (0x3FFF023DUL)
#define VI_ATTR_PXI_IS_EXPRESS                (0x3FFF0240UL)
#define VI_ATTR_PXI_SLOT_LWIDTH               (0x3FFF0241UL)
#define VI_ATTR_PXI_MAX_LWIDTH                (0x3FFF0242UL)
#define VI_ATTR_PXI_ACTUAL_LWIDTH             (0x3FFF0243UL)
#define VI_ATTR_PXI_DSTAR_BUS                 (0x3FFF0244UL)
#define VI_ATTR_PXI_DSTAR_SET                 (0x3FFF0245UL)
#define VI_ATTR_PXI_ALLOW_WRITE_COMBINE       (0x3FFF0246UL)
#define VI_ATTR_TCPIP_HISLIP_OVERLAP_EN       (0x3FFF0300UL)
#define VI_ATTR_TCPIP_HISLIP_VERSION          (0x3FFF0301UL)
#define VI_ATTR_TCPIP_HISLIP_MAX_MESSAGE_KB   (0x3FFF0302UL)
#define VI_ATTR_TCPIP_IS_HISLIP               (0x3FFF0303UL)

|#
