(in-package :visa32)

(define-foreign-library visa32
  (:win32 "visa32.dll"))

;;(use-foreign-library visa32)

(defmacro defvisa32constant (name value &optional doc)
  "Wrapper around `defconstant' which exports the constant."
  `(progn
     (eval-when (:compile-toplevel :load-toplevel :execute)
       (defparameter ,name ,value ,doc))
     (export ',name)))

;; Attributes (platform independent size)
(defvisa32constant +vi_attr_rsrc_class+                  #xBFFF0001)
(defvisa32constant +vi_attr_rsrc_name+                   #xBFFF0002)
(defvisa32constant +vi_attr_rsrc_impl_version+           #x3FFF0003)
(defvisa32constant +vi_attr_rsrc_lock_state+             #x3FFF0004)
(defvisa32constant +vi_attr_max_queue_length+            #x3FFF0005)
(defvisa32constant +vi_attr_user_data_32+                #x3FFF0007)
(defvisa32constant +vi_attr_fdc_chnl+                    #x3FFF000D)
(defvisa32constant +vi_attr_fdc_mode+                    #x3FFF000F)
(defvisa32constant +vi_attr_fdc_gen_signal_en+           #x3FFF0011)
(defvisa32constant +vi_attr_fdc_use_pair+                #x3FFF0013)
(defvisa32constant +vi_attr_termchar+                    #x3FFF0018)
(defvisa32constant +vi_attr_tmo_value+                   #x3FFF001A)
(defvisa32constant +vi_attr_gpib_readdr_en+              #x3FFF001B)
(defvisa32constant +vi_attr_io_prot+                     #x3FFF001C)
(defvisa32constant +vi_attr_dma_allow_en+                #x3FFF001E)
(defvisa32constant +vi_attr_asrl_baud+                   #x3FFF0021)
(defvisa32constant +vi_attr_asrl_data_bits+              #x3FFF0022)
(defvisa32constant +vi_attr_asrl_parity+                 #x3FFF0023)
(defvisa32constant +vi_attr_asrl_stop_bits+              #x3FFF0024)
(defvisa32constant +vi_attr_asrl_flow_cntrl+             #x3FFF0025)
(defvisa32constant +vi_attr_rd_buf_oper_mode+            #x3FFF002A)
(defvisa32constant +vi_attr_wr_buf_oper_mode+            #x3FFF002D)
(defvisa32constant +vi_attr_wr_buf_size+                 #x3FFF002E)
(defvisa32constant +vi_attr_suppress_end_en+             #x3FFF0036)
(defvisa32constant +vi_attr_termchar_en+                 #x3FFF0038)
(defvisa32constant +vi_attr_dest_access_priv+            #x3FFF0039)
(defvisa32constant +vi_attr_dest_byte_order+             #x3FFF003A)
(defvisa32constant +vi_attr_src_access_priv+             #x3FFF003C)
(defvisa32constant +vi_attr_src_byte_order+              #x3FFF003D)
(defvisa32constant +vi_attr_src_increment+               #x3FFF0040)
(defvisa32constant +vi_attr_dest_increment+              #x3FFF0041)
(defvisa32constant +vi_attr_win_access_priv+             #x3FFF0045)
(defvisa32constant +vi_attr_win_byte_order+              #x3FFF0047)
(defvisa32constant +vi_attr_gpib_atn_state+              #x3FFF0057)
(defvisa32constant +vi_attr_gpib_addr_state+             #x3FFF005C)
(defvisa32constant +vi_attr_gpib_cic_state+              #x3FFF005E)
(defvisa32constant +vi_attr_gpib_ndac_state+             #x3FFF0062)
(defvisa32constant +vi_attr_gpib_srq_state+              #x3FFF0067)
(defvisa32constant +vi_attr_gpib_sys_cntrl_state+        #x3FFF0068)
(defvisa32constant +vi_attr_gpbi_hs488_cbl_len+          #x3FFF0069)
(defvisa32constant +vi_attr_cmdr_la+                     #x3FFF006B)
(defvisa32constant +vi_attr_vxi_dev_class+               #x3FFF006C)
(defvisa32constant +vi_attr_mainframe_la+                #x3FFF0070)
(defvisa32constant +vi_attr_manf_name+                   #x3FFF0072)
(defvisa32constant +vi_attr_model_name+                  #xbFFF0077)
(defvisa32constant +vi_attr_vxi_vme_intr_status+         #x3FFF008B)
(defvisa32constant +vi_attr_vxi_trig_status+             #x3FFF008D)
(defvisa32constant +vi_attr_vxi_vme_sysfail_state+       #x3FFF0094)
(defvisa32constant +vi_attr_win_base_addr_32+            #x3FFF0098)
(defvisa32constant +vi_attr_win_size_32+                 #x3FFF009A)
(defvisa32constant +vi_attr_asrl_avail_num+              #x3FFF00AC)
(defvisa32constant +vi_attr_mem_base_32+                 #x3FFF00AD)
(defvisa32constant +vi_attr_asrl_cts_state+              #x3FFF00AE)
(defvisa32constant +vi_attr_asrl_dcd_state+              #x3FFF00AF)
(defvisa32constant +vi_attr_asrl_dsr_state+              #x3FFF00B1)
(defvisa32constant +vi_attr_asrl_dtr_state+              #x3FFF00B2)
(defvisa32constant +vi_attr_asrl_end_in+                 #x3FFF00B3)
(defvisa32constant +vi_attr_asrl_end_out+                #x3FFF00B4)
(defvisa32constant +vi_attr_asrl_replace_char+           #x3FFF00BE)
(defvisa32constant +vi_attr_asrl_ri_state+               #x3FFF00BF)
(defvisa32constant +vi_attr_asrl_rts_state+              #x3FFF00C0)
(defvisa32constant +vi_attr_asrl_xon_char+               #x3FFF00C1)
(defvisa32constant +vi_attr_asrl_xoff_char+              #x3FFF00C2)
(defvisa32constant +vi_attr_win_access+                  #x3FFF00C3)
(defvisa32constant +vi_attr_rm_session+                  #x3FFF00C4)
(defvisa32constant +vi_attr_vxi_la+                      #x3FFF00D5)
(defvisa32constant +vi_attr_manf_id+                     #x3FFF00D9)
(defvisa32constant +vi_attr_mem_size_32+                 #x3FFF00DD) 
(defvisa32constant +vi_attr_mem_space+                   #x3FFF00DE)
(defvisa32constant +vi_attr_model_code+                  #x3FFF00DF)
(defvisa32constant +vi_attr_slot+                        #x3FFF00E8)
(defvisa32constant +vi_attr_intf_inst_name+              #x3FFF00E9)
(defvisa32constant +vi_attr_immediate_serv+              #x3FFF0100)
(defvisa32constant +vi_attr_intf_parent_num+             #x3FFF0101)
(defvisa32constant +vi_attr_rsrc_spec_version+           #x3FFF0170)
(defvisa32constant +vi_attr_intf_type+                   #x3FFF0171)
(defvisa32constant +vi_attr_gpib_primary_addr+           #x3FFF0172)
(defvisa32constant +vi_attr_gpbi_secondary_addr+         #x3FFF0173)
(defvisa32constant +vi_attr_rsrc_manf_name+              #xBFFF0174)
(defvisa32constant +vi_attr_rsrc_manf_id+                #x3FFF0175)
(defvisa32constant +vi_attr_intf_num+                    #x3FFF0176)
(defvisa32constant +vi_attr_trig_id+                     #x3FFF0177)
(defvisa32constant +vi_attr_gpib_ren_state+              #x3FFF0181)
(defvisa32constant +vi_attr_gpib_unaddr_er+              #x3FFF0184)
(defvisa32constant +vi_attr_dev_status_byte+             #x3FFF0189)
(defvisa32constant +vi_attr_file_append_en+              #x3FFF0192)
(defvisa32constant +vi_attr_vxi_trig_support+            #x3FFF0194)
(defvisa32constant +vi_attr_tcpip_addr+                  #xBFFF0195)
(defvisa32constant +vi_attr_tcpip_hostname+              #xBFFF0196)
(defvisa32constant +vi_attr_tcpip_port+                  #x3FFF0197)
(defvisa32constant +vi_attr_tcpip_device_name+           #xBFFF0199)
(defvisa32constant +vi_attr_tcpip_nodelay+               #x3FFF019A)
(defvisa32constant +vi_attr_tcpip_keepalive+             #x3FFF019B)
(defvisa32constant +vi_attr_4882_compliant+              #x3FFF019F)
(defvisa32constant +vi_attr_usb_serial_num+              #x3FFF01A0)
(defvisa32constant +vi_attr_usb_intfc_num+               #x3FFF01A1)
(defvisa32constant +vi_attr_usb_protocol+                #x3FFF01A7)
(defvisa32constant +vi_attr_usb_max_intr_size+           #x3FFF01AF)
(defvisa32constant +vi_attr_pxi_dev_num+                 #x3FFF0201)
(defvisa32constant +vi_attr_pxi_func_num+                #x3FFF0202)
(defvisa32constant +vi_attr_pxi_bus_num+                 #x3FFF0205)
(defvisa32constant +vi_attr_pxi_chassis+                 #x3FFF0206)
(defvisa32constant +vi_attr_pxi_slotpath+                #xBFFF0207)
(defvisa32constant +vi_attr_pxi_slot_lbus_left+          #x3FFF0208)
(defvisa32constant +vi_attr_pxi_slot_lbus_right+         #x3FFF0209)
(defvisa32constant +vi_attr_pxi_trig_bus+                #x3FFF020A)
(defvisa32constant +vi_attr_pxi_star_trig_bus+           #x3FFF020B)
(defvisa32constant +vi_attr_pxi_star_trig_line+          #x3FFF020C)
(defvisa32constant +vi_attr_pxi_src_trig_bus+            #x3FFF020D)
(defvisa32constant +vi_attr_pxi_dest_trig_bus+           #x3FFF020E)
(defvisa32constant +vi_attr_pxi_mem_type_bar0+           #x3FFF0211)
(defvisa32constant +vi_attr_pxi_mem_type_bar1+           #x3FFF0212)
(defvisa32constant +vi_attr_pxi_mem_type_bar2+           #x3FFF0213)
(defvisa32constant +vi_attr_pxi_mem_type_bar3+           #x3FFF0214)
(defvisa32constant +vi_attr_pxi_mem_type_bar4+           #x3FFF0215)
(defvisa32constant +vi_attr_pxi_mem_type_bar5+           #x3FFF0216)
(defvisa32constant +vi_attr_pxi_mem_base_bar0_32+        #x3FFF0221)
(defvisa32constant +vi_attr_pxi_mem_base_bar1_32+        #x3FFF0222)
(defvisa32constant +vi_attr_pxi_mem_base_bar3_32+        #x3FFF0223)
(defvisa32constant +vi_attr_pxi_mem_base_bar4_32+        #x3FFF0224)
(defvisa32constant +vi_attr_pxi_mem_base_bar5_32+        #x3FFF0225)
(defvisa32constant +vi_attr_pxi_mem_base_bar6_32+        #x3FFF0226)
(defvisa32constant +vi_attr_pxi_mem_base_bar0_64+        #x3FFF0228)
(defvisa32constant +vi_attr_pxi_mem_base_bar1_64+        #x3FFF0229)
(defvisa32constant +vi_attr_pxi_mem_base_bar2_64+        #x3FFF022A)
(defvisa32constant +vi_attr_pxi_mem_base_bar3_64+        #x3FFF022B)
(defvisa32constant +vi_attr_pxi_mem_base_bar4_64+        #x3FFF022C)
(defvisa32constant +vi_attr_pxi_mem_base_bar5_64+        #x3FFF022D)
(defvisa32constant +vi_attr_pxi_mem_size_bar0_32+        #x3FFF0231)
(defvisa32constant +vi_attr_pxi_mem_size_bar1_32+        #x3FFF0232)
(defvisa32constant +vi_attr_pxi_mem_size_bar2_32+        #x3FFF0233)
(defvisa32constant +vi_attr_pxi_mem_size_bar3_32+        #x3FFF0234)
(defvisa32constant +vi_attr_pxi_mem_size_bar4_32+        #x3FFF0235)
(defvisa32constant +vi_attr_pxi_mem_size_bar5_32+        #x3FFF0235)
(defvisa32constant +vi_attr_pxi_mem_size_bar0_64+        #x3FFF0238)
(defvisa32constant +vi_attr_pxi_mem_size_bar1_64+        #x3FFF0239)
(defvisa32constant +vi_attr_pxi_mem_size_bar2_64+        #x3FFF023A)
(defvisa32constant +vi_attr_pxi_mem_size_bar3_64+        #x3FFF023B)
(defvisa32constant +vi_attr_pxi_mem_size_bar4_64+        #x3FFF023C)
(defvisa32constant +vi_attr_pxi_mem_size_bar5_64+        #x3FFF023D)
(defvisa32constant +vi_attr_pxi_is_express+              #x3FFF0240)
(defvisa32constant +vi_attr_pxi_slot_lwidth+             #x3FFF0241)
(defvisa32constant +vi_attr_pxi_max_lwidth+              #x3FFF0242)
(defvisa32constant +vi_attr_pxi_actual_lwidth+           #x3FFF0243)
(defvisa32constant +vi_attr_pxi_dstar_bus+               #x3FFF0244)
(defvisa32constant +vi_attr_pxi_dstar_set+               #x3FFF0245)
(defvisa32constant +vi_attr_pxi_allow_write_combine+     #x3FFF0246)
(defvisa32constant +vi_attr_tcpip_hislip_overlap_en+     #x3FFF0300)
(defvisa32constant +vi_attr_tcpip_hislip_version+        #x3FFF0301)
(defvisa32constant +vi_attr_tcpip_hislip_max_message_kb+ #x3FFF0302)
(defvisa32constant +vi_attr_tcpip_is_hislip+             #x3FFF0303)


#|


|#
